---
title: "workshop-10_2023-06-07"
author: "Graycen Mahon"
date: "2023-06-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading in Packages

```{r}
# model packages
library(MASS) # have to read this in before tidyverse 
library(lme4)
library(glmmTMB) # ok if you don't have this - just comment it out

# diagnostics and model info
library(DHARMa)
library(MuMIn)
library(ggeffects)
library(lmtest)
library(broom)

# general usage
library(tidyverse)
library(here)
library(naniar)
library(skimr)
library(GGally)
library(flextable)
```

## Reading in the data:

```{r}
salamanders <- read_csv(here("data", "salamanders.csv"))
```

## Exploring the Dataset:

```{r histogram-of-counts}
ggplot(salamanders, aes(x = count)) +
  geom_histogram(bins = 17)
```

```{r missing-data-visualization}
gg_miss_var(salamanders) # nothing missing!
```

```{r skimming-the-data}
skim(salamanders)
```

```{r}
salamanders %>% 
  select(!site) %>% 
  ggpairs()
```

## build linear models:

```{r}
# linear model, we know this is wrong
salmod1 <- lm(count ~ cover + mined + spp, data = salamanders)

# generalized linear model with Poisson distribution
salmod2 <- glm(count ~ cover + mined + spp, data = salamanders, family = "poisson")
salmod2.a <- glm(count ~ cover + mined + spp, data = salamanders, family = "poisson")

# generalized linear model with negative binomial distribution
salmod3 <- glm.nb(count ~ cover + mined + spp, data = salamanders)
salmod3.a <- glmmTMB(count ~ cover + mined + spp, data = salamanders, family = "nbinom2")

# generalized linear model with Poisson distribution and random effect of site
salmod4 <- glmer(count ~ cover + mined  + spp + (1|site), data = salamanders, family = "poisson")
salmod4.a <- glmmTMB(count ~ cover + mined  + spp + (1|site), data = salamanders, family = "poisson")

# generalized linear model with negative binomial distribution and random effect of site
salmod5 <- glmer.nb(count ~ cover + mined  + spp + (1|site), data = salamanders)
salmod5.a <- glmmTMB(count ~ cover + mined + spp + (1|site), data = salamanders, family = "nbinom2")
```

## Look at residuals

```{r}
# check diagnostics
plot(simulateResiduals(salmod1)) # bad
```

```{r}
plot(simulateResiduals(salmod2)) # bad
```

